### PR TITLE
enable okhttp cache

### PR DESCRIPTION
**Pull request by jimxj**
1. enable okhttp cache to handle cache headers in response
2. Added tests
3. Removed some unused files

### CODE REVIEW

**Comment by jimxj** [comment]
@priteshshah1983 , please review

**Comment by priteshshah1983** [comment]
@jimxj were you able to test caching for attachments?

**Comment by priteshshah1983** [comment]
The changes look good

**Comment by jimxj** [comment]
Yes, it works with attachment.

**Pull request merged**
